WIP: Force HTTPS connection
cornell-dti/course-reviews-react-2.0 pull request #206
Opened 2020-10-23 18:46 UTC by julian-londono

### Summary 

This PR fixes the issue where some users land on the `http://` version of CUReviews.  This leads to problems when submitting a review.

### Test Plan 

Plan to test on a PR deployment created by Heroku

### Notes 

- This _does not_ force HTTPS on localhost, do not expect this behavior

2020-10-24 20:38 UTC, draycfarley approved these changes
Looks good, you can see the effect on https://cureviews-pr-206.herokuapp.com/ for anyone else who wants to try.

2020-10-25 15:56 UTC, khemritolya requested changes
The changes look good. It does in fact force me to redirect to https even when I try to force it to go to http. I just have one concern. On my machine, I now get this strange issue: 
![Screenshot from 2020-10-25 11-50-28](https://user-images.githubusercontent.com/15002444/97112067-a9977100-16b8-11eb-9ebd-04d80005dc2f.png)

I assume that this seems to be caused by this PR. I'm not getting this on the dev heroku deployment : 
![Screenshot from 2020-10-25 11-55-35](https://user-images.githubusercontent.com/15002444/97112179-3e9a6a00-16b9-11eb-9787-49e6668f716f.png)

2020-10-25 17:31 UTC, julian-londono commented
Yup our API key with Google OAuth isn't set up to work with PR deployments by default - updated on the API key side and works for this deployment now @khemritolya

2020-10-25 17:55 UTC, khemritolya approved these changes
Alright, it all looks good now. I checked, and this seems to have fixed the way that I managed to cause the issue.

2020-10-25 18:03 UTC, merged