Used react-toastify for new notifications
cornell-dti/course-reviews-react-2.0 pull request #253
Opened 2021-04-01 20:09 UTC by tmenezes1

### Summary 

Submitting a review now results in either a success or error toast notification, as opposed to alert popups that were used previously.

![image](https://user-images.githubusercontent.com/32271721/113348307-6c3cac80-9304-11eb-8853-764972feedcd.png)
![image](https://user-images.githubusercontent.com/32271721/113348393-85ddf400-9304-11eb-8330-ea78c44c7e22.png)

### Test Plan 

Tested on successful course review submissions

### Notes 

### Breaking Changes

2021-04-01 21:17 UTC, khemritolya requested changes
Looks good overall -- there were some style issues however -- see if you can move it to the center of the screen, and make it larger. In user testing it seems that people miss the popup sometimes if it is in the corner.

2021-04-01 21:21 UTC, juliejeong reviewed
Looks good!! the color is bright so it is easy to catch attention and also the duration of the pop up seems reasonable as well :)

2021-04-03 17:57 UTC, khemritolya reviewed
There are a couple of small issues that I have, see the comments. Seems good otherwise.

2021-04-03 17:57 UTC, khemritolya commented on client/src/ui/Form.jsx
> +        //alert('Thanks for reviewing! New reviews are updated every 24 hours.');
I'm not sure why these comments are still hanging around. They appear in a number of other places as well. It is recommended to get rid of unneeded code.

2021-04-03 17:57 UTC, khemritolya commented on client/src/ui/Form.jsx
> +        //alert("An unknown error occured, please try again.", "danger");
here also

2021-04-03 17:57 UTC, khemritolya commented on client/src/ui/Form.jsx
> +    //alert("You may only submit a review with a @cornell.edu email address, please try again.", "danger");
ditto.

2021-04-03 19:51 UTC, khemritolya approved these changes
Looks good!

2021-04-03 20:12 UTC, merged