Fixes screen sizing and gage sizing
cornell-dti/course-reviews-react-2.0 pull request #273
Opened 2021-05-15 20:07 UTC by tmenezes1

### Summary 

This pull request fixes problematic screen width sizes that were in the range of 990px - 1000px. It also manages the height of the gauges so that it does not overflow and intersect with anything. Note: width 992px is problematic and does not work.

### Test Plan 

Tested locally on multiple screen sizes with widths in the range of 990 to 1000px

### Notes 

### Breaking Changes

2021-05-15 21:08 UTC, khemritolya requested changes
Please to merge in the changes from the main branch,

2021-05-17 20:19 UTC, khemritolya reviewed
Currently attempting to debug this behavior, which only seems to occur on firefox. (Notice the gauge bar is smaller than on production).
![Screenshot_20210517_161000](https://user-images.githubusercontent.com/15002444/118551248-b4d0ed80-b72b-11eb-86bf-9b1a02783d9a.png)

2022-02-04 02:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/course-reviews-react-2.0?pullRequest=273) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/course-reviews-react-2.0?pullRequest=273) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/course-reviews-react-2.0?pullRequest=273) it.</sub>

2022-02-17 18:41 UTC, kungpaogao commented
Fixed in #279

2022-02-17 18:41 UTC, closed without merging