Upgrading to Bootstrap 4
cornell-dti/course-reviews-react-2.0 pull request #282
Opened 2021-10-07 22:45 UTC by jack-farley

### Summary 

This pull request updates CU Reviews from bootstrap 3 to bootstrap 4. Currently, the client is largely updated, except for the class view page, which Andrew is updating and will add on top of this PR. 

- [x] Upgrades to bootstrap 4
- [x] Removes panels
- [x] Updates everything to use the new version of the grid system
- [x] some other minor changes

### Test Plan 

I have tested these updates on many screen sizes from a large monitor to a small window, but I haven't done too much testing on mobile yet.

### Linter Warnings 

Right now I am not seeing any linter warnings for the update. 

### Notes

If you are getting an error after pulling this branch, try removing your node modules and reinstalling.

2021-10-19 02:29 UTC, jack-farley commented on client/src/ui/ClassView.jsx
> +          <div className=".d-none.d-xs-block.d-md-none">
Thanks, good catch. Wasn't working when I tested it, wasn't sure why - this seems to have fixed it though.

2021-11-03 01:48 UTC, kungpaogao requested changes
overall, looks great - looks like this was pretty tedious to do!

biggest thing I noticed (without checking out the branch locally) is that `col-xs` should be just `col` (https://getbootstrap.com/docs/4.0/migration/#grid-system)

2021-11-03 01:48 UTC, kungpaogao commented on client/src/ui/PreviewCard.jsx
> +            <div className="col-lg-4 col-md-4 col-sm-4 col-xs-4 remove-left-padding">
```suggestion
            <div className="col-lg-4 col-md-4 col-sm-4 col-4 remove-left-padding">
```
there's no more `xs` breakpoint, so here and elsewhere `col-xs-{value}` should just be `col-{value}`

2021-11-03 01:48 UTC, kungpaogao commented on client/src/ui/UpdateReview.tsx
> +              <div className="col-md-6 col-sm-12 col-xs-12">
`col-xs` --> `col`

2021-11-17 01:26 UTC, AkashAryal approved these changes
Looks Good! Thanks for the big PR!

2021-11-17 01:31 UTC, kungpaogao approved these changes
looks good :))

2021-11-17 01:34 UTC, merged