ClassView layout (1/3)
cornell-dti/course-reviews-react-2.0 pull request #287
Opened 2021-10-20 01:20 UTC by kungpaogao

### Summary 

This pull request is the first step towards rewriting the `ClassView` page. This PR deals with the layout and styling of `ClassView`.

- removed lots of nesting of components and styles (e.g., `ClassView` directly imports and uses `Form` component)
  - this allows for better layout management - breakpoints and scaling can be set in parent CSS
- redid `Gauge` layout and styling again to make alignment easier
- fixed lots of small visual glitches (e.g., alignment of scroll bar on right side of course reviews, gauge container right-side alignment)
- updated overflow behavior to be more predictable
- removed `CourseCard` component because it's useless

- DO NOT MERGE this into `master` branch - this fix is foundational work for following PRs that will be merged into `kungpaogao/class-view-rewrite`, which will then be merged into `master` as a package
- see **Breaking Changes** section below

### Test Plan 

- mainly visual testing

TODO: screenshots / screen recordings

### Linter Warnings 

n/a

### Notes 

- all this work will probably be rebased onto @jack-farley's Bootstrap 4 work
- we should rethink spacing and how to handle it consistently - right now, I am using pretty arbitrary numbers like `70px` and `35px` based on previous work, but this should be standardized
  - maybe we should look into using CSS variables?? 

### Breaking Changes  

- this current PR is missing several features
  - missing ability to add review on mobile - no buttons or form
  - removed `ResultsDisplayMobile` from `ClassView` (for now)
  - missing scroll interactions (e.g., collapsing top bar on mobile)
- some bugs
  - fixed nested `.container` and `.row` usage in `index.tsx` and children components - this causes the `ResultsDisplay` header to shift left because of negative margins
  - `Form` component doesn't scale super well at the moment, but that will be addressed in future PRs (probably 3/3)

2021-11-10 02:13 UTC, jack-farley requested changes
This looks pretty good to me. Aside from the stuff in breaking changes, the double scroll bar in past reviews is the only thing I saw that might need changes

2021-11-10 02:13 UTC, jack-farley commented on client/src/ui/ClassViewNew.tsx
> +              <CourseReviews
I'm seeing a double scroll bar in the past reviews section, not sure why that is happening.

2021-11-10 02:13 UTC, jack-farley commented on client/src/ui/ClassViewNew.tsx
> +export default function ClassView() {
Great job on rewriting class view - this looks much cleaner!

2021-11-10 02:13 UTC, jack-farley commented on client/src/ui/ClassViewNew.tsx
> +      <div className={`row ${styles.classView}`}>
I like the switch to css modules - seems like this is a good move for the frontend

2021-11-10 02:31 UTC, AkashAryal requested changes
Wow this looks like it was a lot of work! Good job Andrew! The only things I see is that on windows/ubuntu there are scroll bars in the class view as noted by Jack.

2021-12-03 22:22 UTC, jack-farley commented
Not seeing the double scrollbar anymore on windows - good job!

2021-12-06 06:58 UTC, AkashAryal approved these changes
The double scroll bars dont show up in ubuntu anymore. Nice!

2021-12-08 01:35 UTC, jack-farley approved these changes
Looks good!

2021-12-08 01:36 UTC, merged