left profile card
cornell-dti/course-reviews-react-2.0 pull request #293
Opened 2021-11-01 16:55 UTC by michelleli01

### Summary 
I implemented the Figma design for the left profile card part of the user profile page. Right now, the data and information are hard coded in and I have not implemented/connected the backend portion.

- [x] user statistics
- [x] user profile information
- [x] sign out button
- [x] styled components
- [ ] implement backend functionality

### Test Plan 
![image](https://user-images.githubusercontent.com/11303631/139708955-9881b111-b040-40c5-bf7b-5c9c75a6f96f.png)

### Linter Warnings

2021-11-03 01:04 UTC, kungpaogao requested changes
Great use of CSS Modules, functional components, and TypeScript :)

It seems like a lot of styles are from Figma, so I would make sure to test that these behave as expected on different screen sizes. I think you might run into some issues because some width/heights are static values.

2021-11-03 01:04 UTC, kungpaogao commented on client/src/ui/css/ProfileCard.module.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto&display=swap");
put `@import` at top of file

2021-11-20 18:30 UTC, kungpaogao approved these changes
looks good!!

2021-11-20 18:31 UTC, AkashAryal requested changes
There is a conflict in a few files. After you fix that we should be good!

2021-11-20 18:42 UTC, merged