[WIP] Rate limiting
cornell-dti/course-reviews-react-2.0 pull request #315
Opened 2022-02-13 03:46 UTC by michelleli01

### Summary 

This pull request prevents users from abusing the report review functionality by limiting to 3 reports per day. 
- [x] changed the database schema
- [x] added functionality for limiting report reviews
- [ ] tested functionality 

### Test Plan 

### Linter Warnings 

Before this PR (i.e. on the main branch), there are X linter warnings. After my PR, there are Y.

### Notes 

### Breaking Changes  

- Database schema changes: add new lastReported and numTimesReported fields

2022-02-13 03:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/course-reviews-react-2.0?pullRequest=315) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/course-reviews-react-2.0?pullRequest=315) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: AkashAryal<br/>:white_check_mark: AnkitLakkapragada<br/>:x: jack-farley<br/>:x: michelleli01<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/course-reviews-react-2.0?pullRequest=315) it.</sub>

2022-02-13 20:19 UTC, AnkitLakkapragada reviewed
I think it looks good and I liked the new feature of checking how many requests someone has made in the last 24 hours and only letting them post 3 in one day to avoid spam.

2022-02-13 21:46 UTC, kungpaogao reviewed
I know this is still WIP, so I left some pointers on things I noticed

2022-02-13 21:46 UTC, kungpaogao commented on server/endpoints/AdminActions.ts
> +        if (lastReportedTime === oneDay) {
this probably will never be `true` - I think this should be a `>` or `<` comparison (>‿‿<)

2022-02-14 00:09 UTC, juliejeong reviewed
Yes, this is the feature we need!! I'm just a bit confused about numReported. If it reflects the number of reviews a student has reported in the past 24 hours, how does it get reset? Maybe I missed it in the codes.

2022-02-14 00:09 UTC, juliejeong commented on server/endpoints/AdminActions.ts
> +            message: "Reported too many reviews. Try again in 24 hours.",
I really like andrew's suggestion for the message.

2022-03-20 23:52 UTC, AkashAryal requested changes
Left a few comments below!

2022-03-20 23:52 UTC, AkashAryal commented on common/index.d.ts
> +import internal from "events";
What is this for?

2022-03-20 23:52 UTC, AkashAryal commented on server/endpoints/AdminActions.ts
> +  guard: [body("id").notEmpty().isAscii(), body("netId").notEmpty().isAscii()],
Yea I agree. I think we should gate this method behind auth. This makes it so that only people logged in are able to report

2022-03-20 23:52 UTC, AkashAryal commented on server/endpoints/AdminActions.ts
> +          console.log("hello");
Remove the console.log

2022-03-20 23:52 UTC, AkashAryal commented on server/endpoints/AdminActions.ts
> +        if (numReported >= 3 && lastReportedTime > oneDay) {
I dont think this works. I'm thinking. Its invalid if curtime <= lastReported + 24hrs

2022-04-22 20:20 UTC, AkashAryal requested changes
This should be going into master. Is rate-limiting based off of master? Lets make sure thats the case.

2022-04-25 05:33 UTC, closed without merging